-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- DELIVERY Table Create SQL
-- 테이블 생성 SQL - DELIVERY
CREATE TABLE DELIVERY
(
    `DELIVERY_ID`  BIGINT         NOT NULL    AUTO_INCREMENT,
    `STATUS`       VARCHAR(50)    NULL,
    `CITY`         VARCHAR(50)    NULL,
    `STREET`       VARCHAR(50)    NULL,
    `ZIPCODE`      VARCHAR(50)    NULL,
    PRIMARY KEY (DELIVERY_ID)
);


-- MEMBER Table Create SQL
-- 테이블 생성 SQL - MEMBER
CREATE TABLE MEMBER
(
    `MEMBER_ID`  BIGINT         NOT NULL    AUTO_INCREMENT,
    `NAME`       VARCHAR(50)    NULL,
    `CITY`       VARCHAR(50)    NULL,
    `STREET`     VARCHAR(50)    NULL,
    `ZIPCODE`    VARCHAR(50)    NULL,
    PRIMARY KEY (MEMBER_ID)
);

-- 테이블 Comment 설정 SQL - MEMBER
ALTER TABLE MEMBER COMMENT '회원';


-- ITEM Table Create SQL
-- 테이블 생성 SQL - ITEM
CREATE TABLE ITEM
(
    `ITEM_ID`         BIGINT         NOT NULL    AUTO_INCREMENT,
    `NAME`            VARCHAR(50)    NULL,
    `PRICE`           INT            NULL,
    `STOCK_QUANTITY`  INT            NULL,
    `DTYPE`           VARCHAR(50)    NULL,
    `ARTIST`          VARCHAR(50)    NULL,
    `ETC`             VARCHAR(50)    NULL,
    `AUTHOR`          VARCHAR(50)    NULL,
    `ISBN`            VARCHAR(50)    NULL,
    `DIRECTOR`        VARCHAR(50)    NULL,
    `ACTOR`           VARCHAR(50)    NULL,
    PRIMARY KEY (ITEM_ID)
);

-- 테이블 Comment 설정 SQL - ITEM
ALTER TABLE ITEM COMMENT '품목';


-- ORDERS Table Create SQL
-- 테이블 생성 SQL - ORDERS
CREATE TABLE ORDERS
(
    `ORDER_ID`     BIGINT         NOT NULL    AUTO_INCREMENT,
    `MEMBER_ID`    BIGINT         NULL,
    `DELIVERY_ID`  BIGINT         NULL,
    `ORDER_DATE`   DATETIME       NULL,
    `STATUS`       VARCHAR(50)    NULL,
    PRIMARY KEY (ORDER_ID)
);

-- 테이블 Comment 설정 SQL - ORDERS
ALTER TABLE ORDERS COMMENT '주문';

-- Foreign Key 설정 SQL - ORDERS(DELIVERY_ID) -> DELIVERY(DELIVERY_ID)
ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_DELIVERY_ID_DELIVERY_DELIVERY_ID FOREIGN KEY (DELIVERY_ID)
        REFERENCES DELIVERY (DELIVERY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - ORDERS(DELIVERY_ID)
-- ALTER TABLE ORDERS
-- DROP FOREIGN KEY FK_ORDERS_DELIVERY_ID_DELIVERY_DELIVERY_ID;

-- Foreign Key 설정 SQL - ORDERS(MEMBER_ID) -> MEMBER(MEMBER_ID)
ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_MEMBER_ID_MEMBER_MEMBER_ID FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - ORDERS(MEMBER_ID)
-- ALTER TABLE ORDERS
-- DROP FOREIGN KEY FK_ORDERS_MEMBER_ID_MEMBER_MEMBER_ID;


-- CATEGORY Table Create SQL
-- 테이블 생성 SQL - CATEGORY
CREATE TABLE CATEGORY
(
    `CATEGORY_ID`  BIGINT         NOT NULL    AUTO_INCREMENT,
    `PARENT_ID`    BIGINT         NULL,
    `NAME`         VARCHAR(50)    NULL,
    PRIMARY KEY (CATEGORY_ID)
);

-- 테이블 Comment 설정 SQL - CATEGORY
ALTER TABLE CATEGORY COMMENT '카테고리';

-- Foreign Key 설정 SQL - CATEGORY(PARENT_ID) -> CATEGORY(CATEGORY_ID)
ALTER TABLE CATEGORY
    ADD CONSTRAINT FK_CATEGORY_PARENT_ID_CATEGORY_CATEGORY_ID FOREIGN KEY (PARENT_ID)
        REFERENCES CATEGORY (CATEGORY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CATEGORY(PARENT_ID)
-- ALTER TABLE CATEGORY
-- DROP FOREIGN KEY FK_CATEGORY_PARENT_ID_CATEGORY_CATEGORY_ID;


-- CATEGORY_ITEM Table Create SQL
-- 테이블 생성 SQL - CATEGORY_ITEM
CREATE TABLE CATEGORY_ITEM
(
    `CATEGORY_ITEM_ID`  INT       NOT NULL,
    `CATEGORY_ID`       BIGINT    NULL,
    `ITEM_ID`           BIGINT    NULL,
    PRIMARY KEY (CATEGORY_ITEM_ID)
);

-- Foreign Key 설정 SQL - CATEGORY_ITEM(ITEM_ID) -> ITEM(ITEM_ID)
ALTER TABLE CATEGORY_ITEM
    ADD CONSTRAINT FK_CATEGORY_ITEM_ITEM_ID_ITEM_ITEM_ID FOREIGN KEY (ITEM_ID)
        REFERENCES ITEM (ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CATEGORY_ITEM(ITEM_ID)
-- ALTER TABLE CATEGORY_ITEM
-- DROP FOREIGN KEY FK_CATEGORY_ITEM_ITEM_ID_ITEM_ITEM_ID;

-- Foreign Key 설정 SQL - CATEGORY_ITEM(CATEGORY_ID) -> CATEGORY(CATEGORY_ID)
ALTER TABLE CATEGORY_ITEM
    ADD CONSTRAINT FK_CATEGORY_ITEM_CATEGORY_ID_CATEGORY_CATEGORY_ID FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY (CATEGORY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - CATEGORY_ITEM(CATEGORY_ID)
-- ALTER TABLE CATEGORY_ITEM
-- DROP FOREIGN KEY FK_CATEGORY_ITEM_CATEGORY_ID_CATEGORY_CATEGORY_ID;


-- ORDER_ITEM Table Create SQL
-- 테이블 생성 SQL - ORDER_ITEM
CREATE TABLE ORDER_ITEM
(
    `ORDER_ITEM_ID`  BIGINT    NOT NULL    AUTO_INCREMENT,
    `ORDER_ID`       BIGINT    NULL,
    `ITEM_ID`        BIGINT    NULL,
    `ORDER_PRICE`    INT       NULL,
    `COUNT`          INT       NULL,
    PRIMARY KEY (ORDER_ITEM_ID)
);

-- 테이블 Comment 설정 SQL - ORDER_ITEM
ALTER TABLE ORDER_ITEM COMMENT '주문_품목';

-- Foreign Key 설정 SQL - ORDER_ITEM(ITEM_ID) -> ITEM(ITEM_ID)
ALTER TABLE ORDER_ITEM
    ADD CONSTRAINT FK_ORDER_ITEM_ITEM_ID_ITEM_ITEM_ID FOREIGN KEY (ITEM_ID)
        REFERENCES ITEM (ITEM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - ORDER_ITEM(ITEM_ID)
-- ALTER TABLE ORDER_ITEM
-- DROP FOREIGN KEY FK_ORDER_ITEM_ITEM_ID_ITEM_ITEM_ID;

-- Foreign Key 설정 SQL - ORDER_ITEM(ORDER_ID) -> ORDERS(ORDER_ID)
ALTER TABLE ORDER_ITEM
    ADD CONSTRAINT FK_ORDER_ITEM_ORDER_ID_ORDERS_ORDER_ID FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - ORDER_ITEM(ORDER_ID)
-- ALTER TABLE ORDER_ITEM
-- DROP FOREIGN KEY FK_ORDER_ITEM_ORDER_ID_ORDERS_ORDER_ID;